### ISSUE TITLE
Black screen nearly every day

### ISSUE THREAD

**Issue by soenkegissel** [liaoheng/BingWallpaper#1]
I use your latest release and get a black screen nearly every day. If I open the app and update the wallpaper manually it works fine.
Can't you implement a retry functionality if the wallpaper is set unsuccessfully?
Thanks for your work!

**Comment by liaoheng** [comment]
@soenkegissel  you can provide phone model,system version,ROM?before version of the normal?

**Comment by soenkegissel** [comment]
Phone Model Xiaomi Mi4
Android 7.1.2
LineageOS Version 14.1-20171225-NIGHTLY-cancro

**Comment by liaoheng** [comment]
the app was kill by other app,add the app form whitelist.

**Comment by liaoheng** [comment]
before app has been removed from Google Play,new app install form [Google Play](https://play.google.com/store/apps/details?id=me.liaoheng.wallpaper).

**Comment by soenkegissel** [comment]
Wonderful - thanks!
