### ISSUE TITLE
可以增加Unsplash源的壁纸吗？

### ISSUE THREAD

**Issue by snakwu** [liaoheng/BingWallpaper#10]
可以增加Unsplash源的壁纸吗？

**Comment by liaoheng** [comment]
暂时没有这个打算，毕竟名字叫必应壁纸🤔

SnakWu <notifications@github.com> 于 2020年2月10日周一 上午7:02写道：

**Comment by snakwu** [comment]
几应的壁纸分别率没Unsplash高
