### ISSUE TITLE
Wallpapers no longer scroll on home screen

### ISSUE THREAD

**Issue by jeisinge** [liaoheng/BingWallpaper#12]
With the Essential PH-1, I was able to select landscape resolution of 1920 x 1080. This enable only a partial image to be down on my screen. However, as I scrolledmy home screen to the right, more of this image would be shown.

About a month or two ago, this feature stopped working. Instead, I get a static image. I believe it is the same as a portrait 1080 x 1920 image.

A work around is to save the 1920 x 1080 image and then set it as my wall paper manually.

**Comment by liaoheng** [comment]
What ROM do you use?

**Comment by jeisinge** [comment]
I'm not using one - just base.

**Comment by liaoheng** [comment]
Can I copy a feedback info? feedback dialog can get info.

**Comment by jeisinge** [comment]
feedback info ------------------------- 
sdk: 29 device: mata model: PH-1 product: mata rom_name: Essential Products rom_type: 0 rom_version: QQ1A.200105.032 locale: en_US auto_locale: en_US version: 1.7.5 resolution: 1920x1080 sys_resolution: 1316x2560 job: none alarm: false alarm_time:  autoSetMode: Home and lock screen interval: 3
feedback info ------------------------- 


Also, I just tried clearing the cache and data for the app.

And, if you couldn't tell, I love your app! Thank you!

**Comment by liaoheng** [comment]
Thanks for you feedback, the problem has been found, be fixed in the next version.
