### ISSUE TITLE
auto update

### ISSUE THREAD

**Issue by foreteller22** [liaoheng/BingWallpaper#14]
Hi.
I am not sure when this started ( some 2-3 weeks ago ) but update time is changed. 
Before it changed I got auto updates about 11,00 am CET . It was this day actual wallpaper. 
Now is changing about 6.00 am CET and it is yesterday wallpaper for actual day . 
On PC I have new wallpaper about 11,00 am CET as like before on mobile.
My setting before was - optimal
Now I tried all other options but wallpaper doesnt change whole day. ( So timing , nor planning doesnt work )
When I start app it shows new wallpaper as it should be and I'am able to change it. 
Thanks.

------------feedback info------------- 
sdk: 30 device: sargo model: Pixel 3a product: sargo rom_name: Google rom_type: 0 rom_version: RP1A.200720.009 locale: sk_SK auto_locale: sk_SK version: 1.9.11 resolution: 1080x1920 sys_resolution: 1080x2220 job: worker autoSetMode: 0 interval: 3
------------feedback info-------------

**Comment by liaoheng** [comment]
The ‘Optimal’ option uses the ‘[WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager)’ by default, and its execution plan is arranged by the system. It may be that Android 11 changes have related logic.

**Comment by foreteller22** [comment]
Still no change . Any option for auto update doesnt works. Nor scheduler , timer. I wanted to create Macrodroid script but Idk how to create it. I am able only to run app . Is there some script for it. I was able to create desktop shorcut to update wallpaper and lock screen on one touch. But it would be great to work it auto. Thank you

**Comment by liaoheng** [comment]
You can take a look at this [help doc](https://github.com/liaoheng/BingWallpaper/blob/image/HELP.md) first, if you feel troublesome, you can use the 'Live wallpaper' option.

**Comment by foreteller22** [comment]
Hi. Thanks for answering. But I already have battery optimization turned
off. And auto update works but it has changed time. Now it changes about 5
hours sooner.in night local time . so it take yesterday wallpaper. Before
it automatically changed later. There's no change on Microsoft timing. It
was always the same. And live wallpaper alternative does not work
unfortunately.

Dňa st 23. 9. 2020, 12:06 Liaoheng <notifications@github.com> napísal(a):

**Comment by liaoheng** [comment]
Will the app not work at all, or will the update time be delayed? send me with a debug log if you can.

**Comment by foreteller22** [comment]
Hi.
App working like :
When I start it manually it shows actual Bing wallpaper and I can manually
set it.
It auto updates but in different time like before ( now it is 5 or 6 hours
sooner ) So I got yesterday wallpaper. It update like this when I use any
of setting ( Optimal , Scheduler , Live or Timer )
Scheduler option nor Timer doesn't work as should . App is excluded from
battery optimization. Everything worked correctly with Android 11 beta3 on
start of august. Problems begun probably on start of september .When
official Android 11 was released.Or after app update ? Idk exactly.

------------feedback info-------------
sdk: 30 device: sargo model: Pixel 3a product: sargo rom_name: Google
rom_type: 0 rom_version: RP1A.200720.009 locale: sk_SK auto_locale: sk_SK
version: 1.9.12 resolution: 1080x1920 sys_resolution: 1080x2220 job: worker
autoSetMode: 0 interval: 1
------------feedback info-------------


pi 25. 9. 2020 o 10:34 Liaoheng <notifications@github.com> napísal(a):

**Comment by foreteller22** [comment]
Could you please write where exactly I shold looking for debug file. I do not have SD Card on Pixel . And in /mnt/sdcard/Android I am unable open folder data. I use Total Commander.

**Comment by liaoheng** [comment]
Debug log file at: /sdcard/Android/data/me.liaoheng.wallpaper/log/debug_log.txt.
Turn on Enable Debug log option and wait a day, can also then you can use the feedback dialog to send it directly to me.

**Comment by foreteller22** [comment]
Hi . So I sending debuglog. But from time I checked to create debuglog everything works as should be . 
[debug_log.txt](https://github.com/liaoheng/BingWallpaper/files/5288040/debug_log.txt)

**Comment by liaoheng** [comment]
I see the debug log app is running normally, i think the server time is
caused by GMT-8. this time is beyond my control, sorry.

foreteller22 <notifications@github.com> 于 2020年9月27日周日 下午5:32写道：

**Comment by foreteller22** [comment]
OK . It looks works correctly now. Please set this issue as done. Thank you

po 28. 9. 2020 o 12:25 Liaoheng <notifications@github.com> napísal(a):
