### ISSUE TITLE
Please add HD wallpaper resolution

### ISSUE THREAD

**Issue by hayvan96** [liaoheng/BingWallpaper#16]
Hi
I use a Oneplus 6 (enchilada, Lineage OS 17.1), which screen resolution is 1080x2280 (HD).

The proposed resolutions will end into overcropped or overzoomed wallpapers. When viewing the Bing wallpaper in the app, it's perfect, but when applied to the lockscreen wallpaper.

Would it be possible to add that HD resolution ? If not, which existing option would you advice?

thanks for your hard work

**Comment by liaoheng** [comment]
The wallpaper resolution is provided by Bing, Unfortunately, no HD resolution is provided, but UHD resolution has been provided, you can try to use it.

**Comment by hayvan96** [comment]
I didn't know resolutions were provided by Bing.
UHD is way too big and zoomed in :
![Screenshot_20210122-061146](https://user-images.githubusercontent.com/37040583/105449678-249d0300-5c79-11eb-8b9d-538e88ca5404.png)
This is 768x1368

![Screenshot_20210122-061315](https://user-images.githubusercontent.com/37040583/105449736-3d0d1d80-5c79-11eb-8ad3-dcb031332089.png)
This is UHD

![Screenshot_20210122-061335_Starth_Bing_Wallpaper](https://user-images.githubusercontent.com/37040583/105449789-544c0b00-5c79-11eb-9ebd-3040c6a25a30.png)
And this is how it appears in the app

**Comment by liaoheng** [comment]
The wallpaper displayed in the app is cut in the center. The effect of setting the wallpaper on the phone is different from phone to phone. If you want this effect, you can try the `Live wallpaper` mode.

**Comment by hayvan96** [comment]
Actually, yes, it's better, and I've reverted to 1080x1920 + live wallpaper mode, which gives the best result to my eyes on a oneplus 6. I'm closing this issue, thanks for your advices and response.
