### ISSUE TITLE
在设置高于设备分辨率的壁纸的时候会裁剪掉周围一圈

### ISSUE THREAD

**Issue by Genglxy** [liaoheng/BingWallpaper#17]
开发者你好，我的设备是venue 7840，分辨率为2560x1600。。。这个分辨率挺不上不下的，只能选择UHD才能获得比较好的体验，尤其对一个平板来讲，不设置成UHD，在竖屏下左右裁剪掉的时候，常规的横向FHD壁纸会特别糊。
但是在设置到UHD的时候，壁纸周围的一整圈都是被裁剪掉的，用PS看了一下，剩下的地方正好是桌面的分辨率

然后我在桌面上测试了一下，用原图在桌面里设置壁纸就没有这个问题，横竖屏都能刚刚好地铺满屏幕

请问有没有什么办法能在设置壁纸的时候直接按比例铺满整个屏幕？谢谢您的帮忙

![Screenshot_2021-03-06-17-03-22](https://user-images.githubusercontent.com/17978020/110202089-8d46e480-7ea1-11eb-8355-f68136bc0ee9.png)
![Screenshot_2021-03-06-17-02-46](https://user-images.githubusercontent.com/17978020/110202137-bd8e8300-7ea1-11eb-9c53-b5a7e956ff39.png)

**Comment by liaoheng** [comment]
可以试试在设置里面把'每日更新模式'改为动态壁纸模式。

**Comment by liaoheng** [comment]
现在Bing提供的分辨率只有这几种，高分辨率最好使用UHD，之后我会考虑要不要增加一个剪切壁纸的功能。

**Comment by Genglxy** [comment]
很抱歉这么久之后又来回复这个issue，一开始我尝试了动态壁纸模式，但似乎动态壁纸模式下会把壁纸设置成竖屏的分辨率，因此在切换横竖屏后，如图所见，横屏下的壁纸很难受...所以这段时间以来我都使用计划任务模式，但很多壁纸由于没有缩放，放大之后并不清晰，比如今天的这个鸟的壁纸因为本身就比较糊，如后两个图所见，一经过放大在大屏幕的桌面上看着非常扎眼。如果可以的话，您是否可以考虑一下针对UHD在设置壁纸前缩小然后裁剪壁纸到设备横屏或者用户设定的目标分辨率？
![image](https://user-images.githubusercontent.com/17978020/124610226-e56b1300-dea2-11eb-883a-e18b8c33007d.png)
![image](https://user-images.githubusercontent.com/17978020/124612298-cc636180-dea4-11eb-9b66-8b04d9b6072b.png)
![image](https://user-images.githubusercontent.com/17978020/124612344-d2594280-dea4-11eb-8e5f-8e38ac6ff194.png)

**Comment by liaoheng** [comment]
现目前对这种横竖屏切换的支持比较差，如果要优化可能对`动态壁纸`模式优化一下了。
