### ISSUE TITLE
动态壁纸模式下重启后黑屏，以及对于每日更新设置的疑问

### ISSUE THREAD

**Issue by railzy** [liaoheng/BingWallpaper#19]
我的设备是三星s10+，在动态壁纸模式下，重启手机后有可能黑屏不显示bing每日图片，只能选择其他壁纸再打开软件重新设置壁纸，才能正常显示。

`开启每日更新`选项打开后直接弹出设置动态壁纸且选项下显示`动态壁纸`，是意味着每日更新必须使用动态壁纸模式吗？是否可以每日自动更新设置为静态壁纸呢？

**Comment by railzy** [comment]
对于第二个问题，我发现`开启每日更新`后下面显示的文字就是`每日更新设置`中的选项，而`每日更新设置`中的`最佳`其实就是`动态壁纸`？感觉缺少`最佳`这一项的说明让人有些困惑。

**Comment by liaoheng** [comment]
1. 动态壁纸与静态壁纸的不同：静态壁纸模式(计划任务和定时任务)是`系统调度`唤醒应用然后调用系统的壁纸API实现，动态壁纸模式是直接实现的`系统动态壁纸服务`壁纸由应用绘制。
2. 系统重启后应用会加载壁纸，然而这个过程一些手机网络是不可用的，有一定机会失败，可以打开应用设置一次壁纸即可，以后可能会优化一下。
3. 当然可以选择静态壁纸的两种模式，但是会面临手机系统的电池优化产生的延迟或者失效，需要自行配置白名单。

**Comment by railzy** [comment]
> 1. 动态壁纸与静态壁纸的不同：静态壁纸模式(计划任务和定时任务)是`系统调度`唤醒应用然后调用系统的壁纸API实现，动态壁纸模式是直接实现的`系统动态壁纸服务`壁纸由应用绘制。
> 2. 系统重启后应用会加载壁纸，然而这个过程一些手机网络是不可用的，有一定机会失败，可以打开应用设置一次壁纸即可，以后可能会优化一下。
> 3. 当然可以选择静态壁纸的两种模式，但是会面临手机系统的电池优化产生的延迟或者失效，需要自行配置白名单。

懂了，其实主要是由于初始默认选择`最佳`即`动态壁纸`模式，而`开启每日更新`打开后选项下面显示`动态壁纸`，我一开始以为`最佳`、`计划任务`、`定时任务`都是动态壁纸的不同更新策略，以为没有静态壁纸模式。

动态壁纸模式有不需要设置电池优化白名单以及显示适应性更佳的优点，所以`最佳`=`动态壁纸`我挺理解的。不过如果`最佳`和`动态壁纸`是相同的选项，感觉以后可以整合成`动态壁纸（推荐）`，这样应该更加不容易引起误解？

**Comment by liaoheng** [comment]
谢谢你的建议，但是现在`最佳`模式只对主流ROM使用`动态壁纸`，其它还是使用`计划任务`，实际上后者效果更好，而且实际上大部分人并不关注这个的。
