### ISSUE TITLE
wallpaper scrolling issue

### ISSUE THREAD

**Issue by Sbrego** [liaoheng/BingWallpaper#20]
Hi, i'm using a Pixel 5, which has a resolution of 1080x2340 (and i'm sure there are many other phones out there with these "stretched" resolutions) and if i set the 1080x1920 wallpaper this will be zoomed in and swifted to the right in order to allow the wallpaper scrolling.
As this is a not removable function, could you make the wallpaper available with these stretched screen ratio?

**Comment by liaoheng** [comment]
Hi, You try can use the 'Live Wallpaper' mode.
