### ISSUE TITLE
[feature request] swipe up/down to see previous/next picture

### ISSUE THREAD

**Issue by tenzap** [liaoheng/BingWallpaper#21]
Thanks for that great open source app! I used to use the official Microsoft App (com.microsoft.bing.wallpapers) but saving doesn't work anymore so I switched to yours.

Would you implement the following feature ?

When swiping up (finger from bottom to top), I would like to see the previous image
And swipe down the next image.

**Comment by liaoheng** [comment]
Hi, thank you for feedback.
Due to the restriction of the `Bing` server, only the data recently seven days, this function is relatively useless, I will not consider it for the time being.

**Comment by tenzap** [comment]
Thanks. I would find it much easier than to have to go to history to switch the day. I don't check the app everyday, so with this I could easily see the previous ones and save the ones I like. Moreover, unfortunately the access to the actions on a picture displayed from the history is not the same as on the pic of the day. Swipping from the pic of the day would permit the keep the same behavior through the floating button when on an older picture.
