### ISSUE TITLE
[feature request] save in multiple size simultaneously

### ISSUE THREAD

**Issue by tenzap** [liaoheng/BingWallpaper#22]
Right now in the GUI it is possible to select only one picture size when saving the image.
Would it be possible to use "check boxes" instead of radio buttons so that it is possible to save the picture in more than one size ?

This screen to select the sizes is in 2 places:
- settings/resolution
- when viewing a picture from history (size icon)

**Comment by liaoheng** [comment]
I feel that this feature is a bit too bloated for mobile phones, I can consider it.
