### ISSUE TITLE
[feature request] warn if picture is copyright protected

### ISSUE THREAD

**Issue by tenzap** [liaoheng/BingWallpaper#23]
In the official bing wallpaper app of Microsoft, some pictures are not allowed to be set as wallpaper because they are copyright protected. In this case it is also not possible to share/save it.

I think it would be better to inform the user of this when he is on a copyright protected picture and let him choose whether he wants to bypass the value of this flag. Could be either sort of a question when he wants to download/set as wallpaper, and/or an option to set in the settings. Maybe you could also add something like "copyright protected" in the saved filename ?

By narrowing things down, it seems this is as such in the official app when in the JSON file from https://www.bing.com/HPImageArchive.aspx?... has `"wp": false,`

**Example:** [query](https://www.bing.com/HPImageArchive.aspx?format=hp&idx=0&n=10&pid=hp&og=1&IG=D44017F288DA4788ACC9D3C9CA2940D3&IID=SERP.1050&mkt=en_US)

**Result:** [response.json.txt](https://github.com/liaoheng/BingWallpaper/files/6433424/response.json.txt)

**How it looks like in the official app if wp:false :**
![wp_false](https://user-images.githubusercontent.com/46226844/117277803-77817b80-ae60-11eb-881e-63a8c2402de6.jpg)

**How it looks like in the official app if wp:true :**
![wp_true](https://user-images.githubusercontent.com/46226844/117277798-75b7b800-ae60-11eb-8edd-e65cf135ed7f.jpg)

**Comment by liaoheng** [comment]
Thank you for your reminder, i may join a prompt, but these functions will not be stopped.
