### ISSUE TITLE
网络连接错误

### ISSUE THREAD

**Issue by geeklihui** [liaoheng/BingWallpaper#24]
桌面黑屏，无法获取壁纸，网络连接错误。尝试过修改分辨率、切换网络等。

------------feedback info------------- 
sdk: 29 device: HWELE model: ELE-AL00 product: ELE-AL00 rom_name: HUAWEI rom_type: 2 rom_version: EmotionUI_11.0.0 locale: zh_CN_#Hans auto_locale: zh_CN_#Hans version: 1.9.20 resolution: UHD sys_resolution: 1080x2340 job: live_wallpaper autoSetMode: 0 interval: 3
------------feedback info-------------

**Comment by liaoheng** [comment]
应用可以正常加载图片吗？请在设置里面打开`调试日志`，然后操作一下，把日志发一份给我。
