### ISSUE TITLE
Wallpaper is zoomed on homescreen

### ISSUE THREAD

**Issue by knmurthy** [liaoheng/BingWallpaper#26]
With latest update Wallpaper is being zoomed on home screen in vertical position. Checked with OneUI launcher, Microsoft Launcher, Nova Launcher etc. Using live wallpaper mode. @liaoheng
![Screenshot_20210718-101616_One UI Home](https://user-images.githubusercontent.com/17162753/126056103-8547748c-bd80-4efc-9859-538c231aea27.jpg)

**Comment by liaoheng** [comment]
Hi, This problem does exist, the start is normal, and then update the wallpaper will have problems, I will invest this problem.

**Comment by knmurthy** [comment]
> Hi, This problem does exist, the start is normal, and then update the wallpaper will have problems, I will invest this problem.

Thank you for acknowledging the issue. Look forward for an update at the earliest. This app is very nice.

**Comment by liaoheng** [comment]
@knmurthy latest beta version of this problem should be able to be solved, you can have a try.

**Comment by knmurthy** [comment]
> @knmurthy latest beta version of this problem should be able to be solved, you can have a try.

Sorry. I have not followed this. However, for the new update and it's resolved the issue.
