### ISSUE TITLE
无法自动更换壁纸

### ISSUE THREAD

**Issue by StrollStars** [liaoheng/BingWallpaper#29]
以前在Android7的系统上，可以实现自动更换壁纸，给予了读取文件的权限。
现在在Android11的系统上，无法实现自动更换壁纸了，请问是不是跟没有这个权限有关，但是给予权限后，第二次开机又没有了，请问该如何解决？

**Comment by StrollStars** [comment]
可我用的是官方LineageOS 18.1，固件为[OnePlus 8T Firmware Updates For Custom ROMS](https://forum.xda-developers.com/t/oneplus-8t-firmware-updates-for-custom-roms.4298181/)，按理说是符合你的要求的。

**Comment by liaoheng** [comment]
LineageOS也是第三方的， 我测试用的是Pixel，这个系统调度在不同版本不同ROM都不一样，所以不用纠结。

StrollStars ***@***.***> 于2021年10月30日周六 上午11:53写道：

**Comment by StrollStars** [comment]
我一直以为LineageOS算是比较接近Pixel的，先谢谢你的耐心答复了。

**Comment by StrollStars** [comment]
请教个问题，这个应用“存储空间/文件和媒体”的权限是必须的吗？

**Comment by liaoheng** [comment]
和功能有关，默认不需要。

StrollStars ***@***.***> 于2021年11月3日周三 下午9:30写道：

**Comment by StrollStars** [comment]
感谢回复，暂时可以每日更新，先观望看看。
