### ISSUE TITLE
Wallpaper change won't work since last update

### ISSUE THREAD

**Issue by DarkLBP** [liaoheng/BingWallpaper#32]
Hi,
I noticed since last version the wallpaper won't change properly.
If I change it manually to an older wallaper seems to work but when I go to the lastest and click to change it it changes it to an old wallpaper instead of the latest one.

https://www.youtube.com/watch?v=oYaLeUl3k3E&feature=youtu.be

I tried to fix it by force closing the app and opening it again but it just made it worse.
Now I have my phone's default wallpaper and the app will get stuck changing the wallpaper.

https://www.youtube.com/watch?v=DkC16i2q5HU

**Comment by liaoheng** [comment]
Thanks for your feedback, I have found this problem, and the next version will fix it.

**Comment by Helios61** [comment]
Hi, 
i've noticed the same issue with OPPO Find X3 Pro/ Android 12. Only changing manually the wallpaper is working for me. 

Best regards

**Comment by liaoheng** [comment]
Hi,
Is it unable to update all screen wallpapers, or you can't set the lock
screen wallpaper?

Helios61 ***@***.***> 于2022年2月27日周日 20:26写道：

**Comment by Helios61** [comment]
Unfortunately all wallpapers.

**Comment by liaoheng** [comment]
Are you using a live wallpaper mode now?

Helios61 ***@***.***> 于2022年2月28日周一 14:37写道：
