### ISSUE TITLE
Changement automatique impossible

### ISSUE THREAD

**Issue by Millepatou** [liaoheng/BingWallpaper#33]
Bonjour, le changement automatique du fond d'écran ne fonctionne pas automatiquement sur mon pixel 5 j'ai essayé toutes les possibilités, ça ne fonctionne pas par contre sur ma tablette Samsung pas de problème

**Comment by liaoheng** [comment]
@Millepatou Please try the latest beta version first. If you still can't, please open the debug log, send it to me.
