### ISSUE TITLE
程序在手机开机后会强行更改锁屏画面

### ISSUE THREAD

**Issue by yyzh** [liaoheng/BingWallpaper#34]
系统:miui 13
程序在手机开机后会强行更改锁屏画面并关闭miui自带的锁屏画报开关.
我已在设置中调整只允许更新主屏幕的背景.但无效.
需要在每次开机后重新打开锁屏画报的开关让miui重新接管锁屏背景的更换.

**Comment by liaoheng** [comment]
MIUI13现在的锁屏幕逻辑改变了，和原生的逻辑相似，所以在设置壁纸的时候会有两个选项，需要在这里选择只设置主屏幕，如果之前选过全部，可以打开小米画报重新设置一下就可以了，应用的相关设置已经无效了。

yyzh ***@***.***> 于2022年2月22日周二 21:35写道：
