### ISSUE TITLE
matepadpro时间久了无法同步壁纸，重新安装后恢复

### ISSUE THREAD

**Issue by yangyang133** [liaoheng/BingWallpaper#36]
![Screenshot_20220506_200852_me liaoheng wallpaper](https://user-images.githubusercontent.com/33922896/167129375-7cb938db-ebd1-42c9-8d15-aedd1ea10521.jpg)
![Screenshot_20220506_200843_me liaoheng wallpaper](https://user-images.githubusercontent.com/33922896/167129392-42000c96-9220-4698-92ff-2daad4359976.jpg)

#35 
------------feedback info------------- 
sdk: 29 device: HWMRX model: MRX-W29 product: MRX-W29 rom_name: HUAWEI rom_type: 2 rom_version: EmotionUI_11.1.0 locale: zh_CN_#Hans auto_locale: zh_CN_#Hans version: 1.9.43 resolution: UHD sys_resolution: 2560x1600 job: live_wallpaper autoSetMode: 0 interval: 3
------------feedback info-------------

**Comment by liaoheng** [comment]
@yangyang133 请打开应用的调试日志，运行一段时间，然后发给我分析一下。

**Comment by yangyang133** [comment]
试了下debug_log.txt文件始终没有信息

**Comment by liaoheng** [comment]
@yangyang133 现在新版本应该有改善，没有日志说明后面应用被系统杀掉了，可以改用计划任务模式。
