### ISSUE TITLE
"Updating" notification doesn't disappear

### ISSUE THREAD

**Issue by hayvan96** [liaoheng/BingWallpaper#37]
Hi, since the last update, even though the wallpaper is correctly updated, the notification "updating the wallpaper" doesn't automatically disappear. I have to clear it myself. This behaviour started since latest update  (1.9.45). I have this bug on my OP6 (LOS19.1, android 12), but my wife's OP6T (LOS18.1, Android 11) has the same issue since the last update.

**Comment by Peter-maximus** [comment]
I can confirm it starts since last update of app from play store.
It shows the notification every hour from midnight until the new wallpaper is found and set. Then there is no new notiification until midnight.

**Comment by liaoheng** [comment]
I adjusted the notification logic in the current version. I will fix it in the next version, thanks feedback.

**Comment by Peter-maximus** [comment]
it would be great. because I want to be informed by notification only in case something wrong happens as it was before this change.

**Comment by hayvan96** [comment]
Hi, the bug I had reported is still there. It's not what Peter added: it only shows when the wallpaper is being updated. But it doesn't disappear once the wallpaper has been correctly updated.

**Comment by liaoheng** [comment]
@hayvan96 Hi, you can tell me your phone Android version&model?

**Comment by hayvan96** [comment]
> @hayvan96 Hi, you can tell me your phone Android version&model?

LineageOS 19.1 (android 12L) on a oneplus 6 but also android 10 (LineageOS 18) on a redmi note 4

**Comment by liaoheng** [comment]
@hayvan96 It should be a different strategy of updating the notification on LineageOS. I will add some logic to avoid this problem, Thanks feedback.

**Comment by Sternagfonkel** [comment]
I have the same problem, but using a Sony Xperia XA2 and Android 9. So I think it is not related to Lineage OS.
But do we really need a notification "Updating wallpaper..." when everything works as expected? What is the benefit? As @Peter-maximus already said, I think it would be more useful to get a notification if something goes wrong during update.

**Comment by Peter-maximus** [comment]
I can confirm the problem is still there (3 months passed...)
I am using OnePlus and Oxygen OS.
It shows the notification every hour from midnight until the new wallpaper is found and set. Then there is no new notiification until midnight.

**Comment by liaoheng** [comment]
@Peter-maximus This prompt means that the wallpaper setting failed. There should be a problem with the network. 
Can you provide the logs to confirm?
