### ISSUE TITLE
无法开启每日更新

### ISSUE THREAD

**Issue by LiKPO4** [liaoheng/BingWallpaper#38]
点击每日更新后，点击设置没有反应

**Comment by liaoheng** [comment]
@LiKPO4 能反馈一下使用的什么手机rom和Android版本吗

**Comment by LiKPO4** [comment]
魅族18 flyme9 安卓11
具体表现是如果每日更新模式不为计划任务，则开启每日更新的按钮就无法正常工作。但是即便在计划任务模式下开启了每日更新，他还是不会正常更新，只能我每天手动更新。

**Comment by liaoheng** [comment]
使用动态壁纸模式也无法使用吗？计划任务需要系统给足够的权限，可以参考[文档](https://github.com/liaoheng/BingWallpaper/blob/image/HELP.md)。

**Comment by liaoheng** [comment]
@LiKPO4 最新版本对动态壁纸逻辑进行了调整，你可以试试。
