### ISSUE TITLE
设置默认保存分辨率是横屏，但自动下载的是竖屏壁纸，手动下载则正常

### ISSUE THREAD

**Issue by formular2** [liaoheng/BingWallpaper#42]
设备为三星Galaxy S21 Ultra，APP版本为最新版（1.9.49）
如图1，设置的默认保存分辨率是1920x1200（试过设为1920x1080和UHD也有同样问题），但是每天自动下载下来的图片实际上是1080*1920（参见图2，可见下载的图片标题是1920x1200结尾，但实际尺寸是1080x1920）。但是进入APP手动点一次下载，结果就是正确的（图3）
每一天都如此，需要手动下载一次才能得到横屏壁纸
![微信图片_20230322090403](https://user-images.githubusercontent.com/48783498/226775420-67a0f652-97a2-46bb-b792-f99e31a84695.jpg)
![微信图片_20230322090423](https://user-images.githubusercontent.com/48783498/226775486-3e62bec7-613b-4b72-b7d0-9f515d38911f.jpg)
![微信图片_20230322090436](https://user-images.githubusercontent.com/48783498/226775498-20e237c0-d979-47f0-8c07-7c93e0ffc6be.jpg)

**Comment by liaoheng** [comment]
自动下载用的是`默认保存壁纸`参数 @formular2
