### ISSUE TITLE
Can't set wallpaper on lockscreen

### ISSUE THREAD

**Issue by ssrki** [liaoheng/BingWallpaper#45]
Can't set wallpaper on lockscreen
Honor 90 device
Wallpaper on desktop doesn't change automatically

**Comment by liaoheng** [comment]
Please copy the feedback to me，follow the steps:
https://github.com/liaoheng/BingWallpaper/blob/image/HELP.md#feedback

ssrki ***@***.***> 于2024年3月11日周一 21:27写道：
