### ISSUE TITLE
Can not Enable daily update on Xiaomi HyperOS

### ISSUE THREAD

**Issue by Tyi-13** [liaoheng/BingWallpaper#46]
Everything was normal before March 11th, today (March 12th) found that the wallpaper did not update automatically, 
When I opened the app to restart the daily update, I found that it could not be enabled
Clearing the cache and all app data could not be enabled, the network problem has been ruled out

**Comment by liaoheng** [comment]
Please try enabling dynamic wallpaper permission.

Tyi-13 ***@***.***> 于2024年3月12日周二 09:42写道：
