### ISSUE TITLE
Problem with blur

### ISSUE THREAD

**Issue by nikosalonen** [liaoheng/BingWallpaper#49]
Hi

I have set `blur` on for Home screen wallpaper only. Now when I set wallpaper, both Lock screen and Home screen wallpapers are blurred.

**Comment by liaoheng** [comment]
Currently, the `Live wallpaper` mode is not supported. You can choose the `Scheduler` mode, but you need to make some settings on the phone, as follows: https://github.com/liaoheng/BingWallpaper/blob/image/HELP.md#faq
