### ISSUE TITLE
Wrong resolution on Home Screen

### ISSUE THREAD

**Issue by ndetogni** [liaoheng/BingWallpaper#6]
Hi,
I've Huawei P20 Pro with EMUI 9.
The resolution of the wallpaper on the Lock Screen is ok, but on the Home Screen is wrong.
The size is too bigger, it seems to be zoomed.

On the configuration I have:
- Choose set wallpaper resolution: 1080x1920
- Choose save wallpaper resolution: 1080x1920

Can you please help me?

Thank you.

**Comment by liaoheng** [comment]
Can you a screenshot?

**Comment by ndetogni** [comment]
I'm sending you both screen.
One of the Home screen and one of the Lock screen.
![inkedphoto5981121579410632247_li](https://user-images.githubusercontent.com/4746959/52535341-79296b00-2d4d-11e9-9db6-2615f2ae7815.jpg)
![inkedphoto5981121579410632246_li](https://user-images.githubusercontent.com/4746959/52535344-7f1f4c00-2d4d-11e9-8a75-33e4636a9a18.jpg)

**Comment by liaoheng** [comment]
Whether your wallpaper operation is manual or automatic? try to test if another wallpaper is normal.

**Comment by ndetogni** [comment]
It's automatic. Also when I set it manually it appears bigger. With a Wallpaper from my gallery the problem doesn't exist.

**Comment by liaoheng** [comment]
You try can clean cache, again set wallpaper. If the problem persists, please wait for the next automatic wallpaper change.

**Comment by ndetogni** [comment]
Hi, also clearing the cache and set it automatically, I have the problem.

**Comment by liaoheng** [comment]
Ok, i want see you setting, you can open the feedback dialog and click the Copy button, paste it.

**Comment by ndetogni** [comment]
feedback info ------------------------- 
sdk: 28 device: HWCLT model: CLT-L29 product: CLT-L29 rom_name: HUAWEI rom_version: EmotionUI_9.0.0 locale: it_IT auto_locale: it_IT version: 1.3.8 job: none alarm: true alarm_time: 09:15:00.000 autoSetMode: Both interval: 3
feedback info -------------------------

**Comment by liaoheng** [comment]
Since I don't have an EMUI 9 device, I will build a beta version, you can try it out.

**Comment by ndetogni** [comment]
Sounds good. Thank you.

**Comment by liaoheng** [comment]
[app-debug.zip](https://github.com/liaoheng/BingWallpaper/files/2865690/app-debug.zip), unzip the file.

**Comment by ndetogni** [comment]
I've just installed it but the issue persists.

**Comment by liaoheng** [comment]
Try test 'Choose auto set wallpaper mode' to choose 'Home screen'.

**Comment by ndetogni** [comment]
I tried but it doesn't work.

**Comment by liaoheng** [comment]
Can't I update the wallpaper?

**Comment by ndetogni** [comment]
The update worked. But the problem with the resolution it's not fixed.

**Comment by liaoheng** [comment]
That problem may not be solved now, thank you for your feedback, then I will find the reason to fix it.

**Comment by liaoheng** [comment]
@ndetogni, Hello i have a new plan, if you can, please help me test it. Thanks.
[app-debug.zip](https://github.com/liaoheng/BingWallpaper/files/2894505/app-debug.zip)

**Comment by ndetogni** [comment]
Hi. I've just tried, but it doesn't work, Thank you for your support.

**Comment by liaoheng** [comment]
Thank you test.

Nicola De Togni <notifications@github.com> 于 2019年2月23日周六 上午1:40写道：

**Comment by liaoheng** [comment]
I upgraded to 9.0, the result of the test: EMUI will scale the main screen and lock screen wallpaper. So I can't handle this problem, sorry.

**Comment by ndetogni** [comment]
ok. This is a bad experience for us with EMUI.
Anyway, thank you for your support.
