### ISSUE TITLE
Wrong resolution - zoomed

### ISSUE THREAD

**Issue by foreteller22** [liaoheng/BingWallpaper#7]
When I use resolution 1920 x 1080 ( or other landscape ) picture is zoomed . And zoom is out of center of picture.
This is when I use default launcher on Pixel 3a on Android Pie , or Android 10 .
When I use Nova launcher picture is correct.
I tried clear cache , change auto ,also diferent services  and other lanscape resolutions.

feedback info -------------------------
sdk: 29 device: sargo model: Pixel 3a product: sargo rom_name: Google rom_version: QP1A.190711.020 locale: sk_SK auto_locale: sk_SK version: 1.5.7 resolution: 1920x1080 job: google_service alarm: false alarm_time:  autoSetMode: Home and lock screen interval: 3
feedback info -------------------------

**Comment by liaoheng** [comment]
I don't understand the question you said, can you take a screenshot?

foreteller22 <notifications@github.com> 于2019年9月4日周三 下午2:48写道：

**Comment by foreteller22** [comment]
Hallo
I attached files . This mobile phone backgrounds are only halves . I use 2
sides on home screen.
But you can see they are different . And pixel launcher background is
shifted more left.

st 4. 9. 2019 o 10:37 NatLeng <notifications@github.com> napísal(a):

**Comment by liaoheng** [comment]
Pixel launcher does not support fixed desktop wallpapers, using 1080x1920 resolution is normal, and Nova launcher has options to support.
![device-2019-09-05-152404](https://user-images.githubusercontent.com/10915809/64321590-6d580b80-cff3-11e9-8d8f-02e975dcf55f.png)
