### ISSUE TITLE
壁纸保存失败

### ISSUE THREAD

**Issue by Wells-yuan** [liaoheng/BingWallpaper#8]
你好，

我的手机是小米8，系统是PixelExprience最新的安卓10beta版。
上一次更新BingWallpaper后发现保存壁纸会提示保存失败，我已经给了软件存储空间的权限，今天更新软件后，依旧提示保存壁纸失败，壁纸保存不成功。
望修复！

feedback info ------------------------- 
sdk: 29 device: dipper model: MI 8 product: dipper rom_name: Xiaomi rom_version: QP1A.191005.007 locale: zh_CN_#Hans auto_locale: zh_CN_#Hans version: 1.6.2 resolution: 1080x1920 job: none alarm: false alarm_time:  autoSetMode: 桌面和锁屏 interval: 3
feedback info -------------------------

**Comment by liaoheng** [comment]
清除缓存再试试，或者打开日志看看有什么错误？

Wells-yuan <notifications@github.com> 于 2019年10月25日周五 下午3:03写道：

**Comment by Wells-yuan** [comment]
清除缓存过，也下载重装过，问题还是在。
看过日志，日志文件里面空白内容

**Comment by liaoheng** [comment]
好的，我会去检查一下。

Wells-yuan <notifications@github.com> 于 2019年10月25日周五 下午6:42写道：

**Comment by liaoheng** [comment]
我会发一个新的beta版本，应该会解决这个问题，可以试一下。

liaoheng <liaohengcn@gmail.com> 于2019年10月26日周六 下午7:13写道：

**Comment by Wells-yuan** [comment]
谢谢！辛苦了！问题已解决！
