### ISSUE TITLE
Wallpaper not zoomed on display larger than FullHD

### ISSUE THREAD

**Issue by 0kommanix** [liaoheng/BingWallpaper#9]
I have a Samsung Galaxy Tab A (2019) SM-T510 which features an unusual resolution of 1920x1200 pixels. It seems that the wallpaper is not zoomed (at least on the lockscreen), leaving a 180 pixel black bar at the top of the screen.

Downloading the wallpaper and setting it via system results in correctly zoomed and applied wallpaper.

This might be a Samsung bug as I experience the same in all of the other Bing wallpaper apps I tried from the play store. But maybe there is a way to tell Android to stretch the wallpaper or as a workaround the picture could be stretched to the device's native display resolution by the app before being applied?

feedback info ------------------------- 
sdk: 28 device: gta3xlwifi model: SM-T510 product: gta3xlwifixx rom_name: samsung rom_type: 0 rom_version: PPR1.180610.011.T510XXU2ASK5 locale: en_US auto_locale: en_US version: 1.6.8 resolution: 1920x1080 job: none alarm: false alarm_time:  autoSetMode: Lock screen interval: 12
feedback info -------------------------

**Comment by liaoheng** [comment]
In theory, the setting the wallpaper all should call system API, it should work fine. can you try the home screen is it normal?

**Comment by 0kommanix** [comment]
Tried setting homescreen and the result is even more surprising with black borders above and to the left. I'm using NovaLauncher and setting the downlaoded wallpaper through NovaLauncher is applying the wallpaper correctly.

**Comment by liaoheng** [comment]
Are you using landscape screen? you can try set wallpaper at vertical screen, is it normal?

**Comment by 0kommanix** [comment]
Yes, I use my tablet in landscape. I tried setting in portrait as well. The wallpaper is somehow stretched but when I rotate the tablet back to landscape, the same black bars result. Seems like the wallpaper is applied exactly the same as if holding the tablet in portrait. Again, when applying any wallpaper through system preferences or via Launcher (which uses the system dialog as well I assume), the wallpapers gets set correctly.

**Comment by liaoheng** [comment]
What is the effect if you use a low-resolution wallpaper such as 1366x768? the wallpaper provided by Bing is lower than the screen resolution, and the wallpaper will be distorted if it is forced to zoom. i will to think about this problem, but thanks for your feedback.

**Comment by 0kommanix** [comment]
I tried again with wallpaper resolution 1280x720 and tablet in landscape. This time, I get black borders at the top (as before) but also at the right side.
Wallpaper resolution 1366x768 results in the usual top black borders only.

If you would zoom the picture keeping its aspect ratio but match or exceed width and height of the screen's native resolution, the wallpaper might be applied correctly. Unfortunately I can't test this scenario because I can't reproduce the black bars when setting wallpaper via system.

In the end I guess it's a Samsung OneUI bug that eventually needs to be addressed by Samsung.

**Comment by liaoheng** [comment]
I found that Bing has 1920x1200 wallpapers, you can try the v1.6.9 beta version

**Comment by 0kommanix** [comment]
Thanks for the Beta. Tried the wallpaper at 1920x1200 and unfortunately, this results in black bars at the top and on the right side, with the picture slightly zommed out.

Looks to me like definitely a bug in how Samsung OneUI handles setting wallpapers and very likely that there is no workaround for this bug.

Thanks anyway for your quick response and the time you've spent in tracing down this bug.

**Comment by liaoheng** [comment]
Ok, that it should be a "One UI" problem, I will attention to it later.

**Comment by 0kommanix** [comment]
I check the latest version and it somehow improved.,

I still see the black bar but it is now located at the bottom of the display and therefore much less intrusive. Unfortunately still not filling the entire screen regardless of protrait/landscape and what resolution I choose.

**Comment by liaoheng** [comment]
Thank you test, i will continue to try this question.

0kommanix <notifications@github.com> 于 2020年6月13日周六 下午8:06写道：

**Comment by 0kommanix** [comment]
Today I received the Android10 / OneUI2.0 update for my tablet and the wallpaper gets applied correctly now on the lock screen as well.

So I think this is either a bug with OneUI1.x or Android 9 and we can close this issue as most tablets should eventually get the update.

Thanks for your support!
